# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# Perfection

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build 
    # - run: npm test
    # - name: Upload build and .svelte-kit folder
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: svelte-kit
    #     # if-no-files-found: error
    #     path: .svelte-kit/
    - run: ls -R
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: shroomcontrol-website-artifact
        path: |
          build
          package.json


  deploy-prod:

    runs-on: ubuntu-latest
    environment: prod
    needs: build

    steps:
    - name: "Download Artifact"
      uses: actions/download-artifact@v3
      with:
        name: shroomcontrol-website-artifact

    - run: ls -R

    - name: Upload
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "build/*, package.json"
        target: "/var/www/shroomcontrol.warumhalbmast.de"
        rm: true

    - name: install dependencies and start node
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /var/www/shroomcontrol.warumhalbmast.de
          npm install
          forever start build
